apiVersion: v1
kind: Namespace
metadata:
  name: infra
---
apiVersion: v1
kind: Namespace
metadata:
  name: databases
  labels:
    purpose: stateful
---
apiVersion: v1
kind: Namespace
metadata:
  name: apps
  labels:
    purpose: stateless
---
apiVersion: v1
kind: Namespace
metadata:
  name: ml
  labels:
    purpose: heavy-compute
