apiVersion: apps/v1
kind: Deployment
metadata:
  name: flashdeutsch-vocab
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flashdeutsch-vocab
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: flashdeutsch-vocab
    spec:
      nodeSelector:
        kubernetes.io/hostname: elitedesk-node1
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: nginx
          image: ghcr.io/tusher16/flashdeutsch-vocab:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "50m"
              memory: "32Mi"
            limits:
              cpu: "100m"
              memory: "64Mi"
